### ISSUE TITLE
Installation issues OS X 10.10.5

### ISSUE THREAD

**Issue by Jakobovski** [enthought/pyql#109]
Thanks for making such an awesome library.

I am having some issues with installing the library on OS X 10.10.5. The make completes successfully, but many tests fail with 

`failed to import test module: quantlib...`

Any ideas on how to fix or troubleshoot the issue?

**Comment by dpinte** [comment]
@Jakobovski  Could you give some exact output of what you exactly do? + the dependencies you used (version of QL, boost, python, ...)

**Comment by Jakobovski** [comment]
I ended up just installing it on a Ubuntu VM.
