### ISSUE TITLE
Work on overloaded Constructors?

### ISSUE THREAD

**Issue by smallnamespace** [enthought/pyql#112]
A lot of QL classes have overloaded constructors, e.g. `FixedRateBond`, [`Schedule`](http://quantlib.org/reference/class_quant_lib_1_1_schedule.html), etc. It seems like PyQL went down the route of exposing the simplest constructor, but sometimes I have the need for the more generic version (e.g. for `Schedule`, I want to define cashflows on specific dates rather than the default start, end, tenor).

Have you given any thought to how you want to handle the overloaded constructors? Some options would be:
  1. default args on ```__init__```
  2. making them class methods
  3. or some classes, wrapping the QL helper classes
  4. An uglier option would be changing ```___init___``` to take args/kwargs and dynamically dispatching, but that's very un-Pythonic

If you have some guidance for me, I'd be happy to wrap up the constructor signatures I'm interested in and submit a PR.

**Comment by dpinte** [comment]
@smallnamespace when needed, we have been using classmethods to do the dispatching to the appropriate C++ constructor. It is not a clear policy over the library so far but we should more than likely go that route. 

One example: https://github.com/enthought/pyql/blob/master/quantlib/termstructures/yields/rate_helpers.pyx#L118

**Comment by smallnamespace** [comment]
@dpinte It looks like QL has a [MakeSchedule](http://quantlib.org/reference/class_quant_lib_1_1_make_schedule.html) helper class, but it 1) doesn't really fulfill a need in Python and 2) doesn't expose the `vector<Date>` parameter.

Would you prefer:
1. An additional `@classmethod` on the Cython `Schedule` class
2. A backwards-compatible change to the `__init__` method (add `dates` to the end of the parameter list, and manually dispatch to the correct C++ constructor)

**Comment by dpinte** [comment]
@smallnamespace I would suggest going for a `classmethod`.

**Comment by smallnamespace** [comment]
@dpinte Thanks for the feedback, PR at https://github.com/enthought/pyql/pull/113
