### ISSUE TITLE
Expose CPIBond class

### ISSUE THREAD

**Issue by ceaza** [enthought/pyql#121]
CPI bonds normally form a key part of many fixed income portfolios.

[https://github.com/lballabio/QuantLib/blob/master/ql/instruments/bonds/cpibond.cpp](url)

**Comment by ceaza** [comment]
@dpinte what tools would one use to do this?

**Comment by dpinte** [comment]
@ceaza you would need to write the same kind of cython wrappers as we did for the various instruments that are exposed through pyql. For example here are the standard bonds: https://github.com/enthought/pyql/blob/master/quantlib/instruments/bonds.pyx

**Comment by ceaza** [comment]
And the type of tools you used to make sure it all works. For example would
one have to put the wrappers together, then compile using print statements
for error tracking or are there better ways of doing this through an IDE?

**Comment by dpinte** [comment]
@ceaza you'll definitely need an IDE. Using print statements for error tracking is not the best way to do things. PyQL has a decent test suite and you would test your developments by implementing a suite of tests that cover the new code you're writing. 

On what platform are you? The compilation steps are quite simple as Python does most of it for you byt you'll need a local development version of Quantlib, etc.

**Comment by ceaza** [comment]
I could use either platform, but at work on Windows. Agreed print
statements would be very tedious, hence the question. So which IDE will
interpret  .pxd and .pyx cython files? PyCharm perhaps or is there a plugin
for spyder? I now see the tests in pyql/quantlib/test/.

**Comment by dpinte** [comment]
Pycharm will work fine. Spyder too. You'll probably have to play with the command line for the compilation steps. Windows is the hardest platform as it requires a custom build of QuantLib to run properly. I can provide pre-built dll's for some versions of QL if you want. Also, depending on your Python version, the MSVC compiler you must use is different (MSVC2008 for Python 2.7, 2010 for < 3.5 and 2015 for >= 3.5)

**Comment by dpinte** [comment]
@ceaza feel free to contact me by e-mail if you need more technical details.

**Comment by thrasibule** [comment]
This is exposed now: http://docs.enthought.com/pyql/_autosummary/quantlib.instruments.bonds.CPIBond.html#quantlib.instruments.bonds.CPIBond
