### ISSUE TITLE
Problem with Python examples - american_option

### ISSUE THREAD

**Issue by rspadim** [enthought/pyql#201]
Hi guys, i compiled the quallib and pyql from source, i'm trying to execute the first example notebook (american_option) but my output is:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b50cbb45b989> in <module>()
      8 """
      9 from __future__ import print_function
---> 10 from quantlib.instruments.api import AmericanExercise, VanillaOption, Put
     11 from quantlib.instruments.payoffs import PlainVanillaPayoff
     12 from quantlib.pricingengines.api import BaroneAdesiWhaleyApproximationEngine, FDAmericanEngine

/usr/local/lib/python3.5/dist-packages/quantlib-0.1-py3.5-linux-x86_64.egg/quantlib/instruments/api.py in <module>()
----> 1 from .bonds import FixedRateBond, ZeroCouponBond, FloatingRateBond
      2 from .credit_default_swap import CreditDefaultSwap, SELLER, BUYER
      3 from .option import EuropeanExercise, AmericanExercise, VanillaOption
      4 from .option import DividendVanillaOption, EuropeanOption
      5 from .payoffs import Put, Call, PlainVanillaPayoff, PAYOFF_TO_STR

ImportError: /usr/lib/libQuantLib.so.0: undefined symbol: _ZN8QuantLib9sessionIdEv

Any idea what can be wrong? 

install quantlib:
./configure --program-prefix=/usr/ --enable-openmp --enable-error-lines --enable-negative-rates --enable-sessions --enable-examples --enable-benchmark --enable-intraday
make
make install

install pyql:
python3 setup.py --verbose build
python3 setup.py --verbose install

**Comment by rspadim** [comment]
python3 --version
Python 3.5.2

ubuntu 16.04 - intel i7 machine

**Comment by dpinte** [comment]
@rspadim you've used the flag `--enable-sessions` which requires you to provide a `sessionId` function in the namespace `QuantLib`. This is not done by pyql and likely the cause of your undefined symbol

See https://github.com/lballabio/QuantLib/blob/master/ql/userconfig.hpp#L67 for more details:
```
/* Define this to have singletons return different instances for
   different sessions. You will have to provide and link with the
   library a sessionId() function in namespace QuantLib, returning a
   different session id for each session.*/
#ifndef QL_ENABLE_SESSIONS
//#   define QL_ENABLE_SESSIONS
#endif
```

**Comment by rspadim** [comment]
Nice, thanks @dpinte !
