### ISSUE TITLE
Adding OISRateHelpers 

### ISSUE THREAD

**Issue by AUK1939** [enthought/pyql#250]
Hi I'm trying to expose OvernightRateHelper from quantlib via pyql (which I was hoping to add back to the repo once complete). I followed the docs and created the following files (see below)

_ois_rate_helper.pxd 
ois_rate_helper.pyx

However when trying to wrap this code (python setup.py wrap). I get the following error:

Compiling quantlib\termstructures\yields\ois_rate_helper.pyx because it changed.
[1/1] Cythonizing quantlib\termstructures\yields\ois_rate_helper.pyx

Error compiling Cython file:
------------------------------------------------------------
...
                       Period forward_start = Period(0, Days), # = 0 * Days
                       Spread overnight_spread = 0.0):

        self._thisptr = shared_ptr[_rh.RateHelper](
                                                 ^
------------------------------------------------------------

quantlib\termstructures\yields\ois_rate_helper.pyx:41:50: no suitable method found
Traceback (most recent call last):
  File "setup.py", line 248, in <module>
    ext_modules = collect_extensions(),
  File "setup.py", line 177, in collect_extensions
    compiler_directives=CYTHON_DIRECTIVES, nthreads = 4)
  File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 1026, in cythonize
    cythonize_one(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 1146, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: quantlib\termstructures\yields\ois_rate_helper.pyx

The error `ois_rate_helper.pyx:41:50: no suitable method found` is not clear to me. Does it mean that I have not managed to match the function signature exactly in the pyx file? If so how can I determine which is the offending parameter? 

The cython declaration file 

/* _ois_rate_helper.pxd */

```
include '../../types.pxi'

from libcpp cimport bool

from quantlib._quote cimport Quote
from quantlib.handle cimport shared_ptr, Handle
from quantlib.time._period cimport Period, Frequency
from quantlib.termstructures.yields._rate_helpers cimport RelativeDateBootstrapHelper
from quantlib.indexes._ibor_index cimport OvernightIndex
from quantlib.time._calendar cimport Calendar
from quantlib.time._businessdayconvention cimport BusinessDayConvention

cimport quantlib.termstructures._yield_term_structure as _yts

cdef extern from 'ql/termstructures/yield/oisratehelper.hpp' namespace 'QuantLib':
    cdef cppclass OISRateHelper(RelativeDateBootstrapHelper):
        OISRateHelper(Natural settlementDays,
                      Period& tenor, # swap maturity
                      Handle[Quote]& fixedRate,
                      shared_ptr[OvernightIndex]& overnightIndex,
                      # exogenous discounting curve
                      Handle[_yts.YieldTermStructure]& discountingCurve, # = Handle<YieldTermStructure>()
                      bool telescopicValueDates, # False
                      Natural paymentLag, # = 0
                      BusinessDayConvention paymentConvention, # = Following
                      Frequency paymentFrequency, #  = Annual
                      Calendar& paymentCalendar, # = Calendar()
                      Period& forwardStart, # = 0 * Days
                      Spread overnightSpread) except + # = 0.0
```

The cython definition file 

/* ois_rate_helper.pyx */

```
include '../../types.pxi'

from libcpp cimport bool

from cython.operator cimport dereference as deref

from quantlib.handle cimport shared_ptr, Handle, static_pointer_cast
from quantlib.quotes cimport Quote, SimpleQuote
from quantlib.time.date cimport Period
from quantlib.termstructures.yields.rate_helpers cimport RelativeDateRateHelper
from quantlib.indexes.ibor_index cimport OvernightIndex
from quantlib.termstructures.yield_term_structure cimport YieldTermStructure
from quantlib.time.calendar cimport Calendar

cimport _ois_rate_helper as _orh
cimport _rate_helpers as _rh
cimport quantlib._quote as _qt
cimport quantlib.indexes._ibor_index as _ib
from quantlib.time._businessdayconvention cimport ( BusinessDayConvention, Following )
from quantlib.time._period cimport Frequency, Days
cimport quantlib.termstructures._yield_term_structure as _yts

cdef class OISRateHelper(RelativeDateRateHelper):

    def __init__(self, Natural settlement_days,
                       Period tenor, # swap maturity
                       Quote fixed_rate,
                       OvernightIndex overnight_index not None,
                       # exogenous discounting curve
                       YieldTermStructure ts not None=YieldTermStructure(), 
                       bool telescopic_value_dates = False, 
                       Natural payment_lag = 0,
                       BusinessDayConvention payment_convention = Following,
                       Frequency payment_frequency = Frequency.Annual,
                       Calendar payment_calendar = Calendar(), 
                       Period forward_start = Period(0, Days), 
                       Spread overnight_spread = 0.0):

        self._thisptr = shared_ptr[_rh.RateHelper](
            new _orh.OISRateHelper(
                settlement_days,
                deref(tenor._thisptr),
                Handle[_qt.Quote](fixed_rate._thisptr), 
                static_pointer_cast[_ib.OvernightIndex](overnight_index._thisptr),
                ts._thisptr,
                telescopic_value_dates,
                payment_lag,
                <_rh.BusinessDayConvention> payment_convention,
                <Frequency> payment_frequency,
                deref(payment_calendar._thisptr),
                deref(forward_start._thisptr),
                overnight_spread
            ))
```

**Comment by thrasibule** [comment]
Do you have just one constructor defined in _ois_rate_helper.pxd for OISRateHelper? Sometimes cython gets confused when there are multiple. If you just have one, then it should just be a matter of making sure the parameters match like you said. I don't know of an easy way to know the offending parameter unfortunately.

**Comment by Asad1939** [comment]
Yes I only have one constructor defined. 

Is it just me or this the hard part of programming these cython interfaces? (was going well before this issue). Is there any way to narrow down the offending parameters? I have a feeling I'm not handling the enum types correctly (BusinessDayConvention). But I haven't had much luck tinkering with it.

**Comment by thrasibule** [comment]
I've found the error: in _ois_rate_helper.pxd, OISRateHelper needs to derive from RelativeDateRateHelper not RelativeDateBootstrapHelper. Next time please push what you have in a branch on your own fork, that will make it easier for me to reproduce what you're seeing.

**Comment by AUK1939** [comment]
Thanks that solved the issue (not sure how I missed that). Subsequently I was able to build the EONIA discount curve in pyql.  

However I think there might be a bug in the wrapper, Here's a simple example of how to reproduce

```
from quantlib.settings import Settings
from quantlib.time.date import October
from quantlib.time.api import Date, Annual, Period, Unadjusted, Thirty360, Actual360
from quantlib.quotes import SimpleQuote
from quantlib.time.calendars.target import TARGET
from quantlib.termstructures.yields.api import SwapRateHelper
from quantlib.indexes.api import Euribor6M
from quantlib.termstructures.yields.api import ( PiecewiseYieldCurve, BootstrapTrait, Interpolator )

# Note the evaluation date
Settings.instance().evaluation_date = Date(3, October, 2014)

# create some swap helpers 
helpers = [SwapRateHelper.from_tenor(SimpleQuote(rate/100.),
                          Period(*tenor),
                          TARGET(),
                          Annual,
                          Unadjusted,
                          Thirty360(),
                          Euribor6M())
           for tenor, rate in [((2, Years), 0.201),
                               ((3, Years), 0.258),
                               ((5, Years), 0.464),
                               ((10, Years), 1.151),
                               ((15, Years), 1.588)]]

# build the curve
curve = PiecewiseYieldCurve(BootstrapTrait.ForwardRate, Interpolator.Linear, 0, TARGET(), helpers, Actual360())

# For some reason the reference date of the curve is 2018-10-11 (which is todays date)
curve.reference_date
>> Date('2018-10-11T00:00:00,000000')
```
This is the swig equivalent code is below which gives the correct reference date to the curve. Thus either I'm either not converting the code correctly to pyql or there is a bug in the wrapper. 

```
from QuantLib import *
Settings.instance().evaluationDate = Date(3, October, 2014)
helpers = [SwapRateHelper(QuoteHandle(SimpleQuote(rate/100.)),
                          Period(*tenor),
                          TARGET(),
                          Annual,
                          Unadjusted,
                          Thirty360(),
                          Euribor6M())
           for tenor, rate in [((2, Years), 0.201),
                               ((3, Years), 0.258),
                               ((5, Years), 0.464),
                               ((10, Years), 1.151),
                               ((15, Years), 1.588)]]
curve1 = PiecewiseFlatForward(0, TARGET(), helpers, Actual360())
print(curve1.referenceDate())
# >> October 3rd, 2014
```

Thanks for the suggestion regarding forking. This is my first github interaction; shall I submit my code to the main repo or keep it in a fork?

**Comment by thrasibule** [comment]
This is a bug with Settings. Depending on how you compiled pyql Settings is not really a singleton. so even though you set the evaluationDate to Date(3, October, 2014), there is another Settings object that get initialized in the curve. I don't understand it very well, so it might be hard to fix. There was a bug with python 3.7 if it was compiled with lto, but I've submitted a fix. Where are you running this code? It should work on Linux.  For instance your code works fine for me on Arch linux. It might be helfpful if you could report the command line incantation that gets generated when you compile pyql. For instance this is what I have

`g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=4 -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.7/quantlib/time/schedule.o -L/usr/local/lib -L/usr/lib -L/usr/lib -lQuantLib -lpython3.7m -o /home/guillaume/projects/pyql/quantlib/time/schedule.cpython-37m-x86_64-linux-gnu.so -Wl,--strip-all`

**Comment by thrasibule** [comment]
Regarding your contributions, once you're happy with, you should definitely submit a pull request to this repo. @dpinte is very responsive and will be happy to merge it I'm sure.

**Comment by AUK1939** [comment]
I working on a Windows 10 box with Anaconda x64 (Python 3.6.5).  

The command line incantation used to build was: 
building 'quantlib.cashflow' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -D__WIN32__ -DWIN32 -DNDEBUG -D_WINDOWS -DNOMINMAX -DWINNT -D_WINDLL -D_SCL_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -IC:\libraries\ORE_2015\QuantLib -IC:\libraries\boost_1_68_0 -I. -I./cpp_layer -IC:\ProgramData\Anaconda3\lib\site-packages\numpy\core\include -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /Tpquantlib\cashflow.cpp /Fobuild\temp.win-amd64-3.6\Release\quantlib\cashflow.obj /GR /FD /Zm250 /EHsc
cashflow.cpp

**Comment by thrasibule** [comment]
I was afraid of that... I couldn't make it work on windows, but we can try! I assume the tests are not working either? If you do "make tests" I suspect you will have other issues with the date being moved inside Settings.

**Comment by thrasibule** [comment]
Oh and how did  you compile quantlib on windows?

**Comment by AUK1939** [comment]
I built Quantlib from the visual studio IDE (x64 release version with Boost 1.68). The only user config I changed was QL_HIGH_RESOLUTION_DATE. I haven't tried "make tests", will probably need to use nmake or cmake.

**Comment by dpinte** [comment]
Windows has been a nightmare with the Singleton problem. I had found a working solution for Python2 which did not work on Python 3. We had to patch QL, generate a dll, etc. I unfortunately does not have the time to look into this issue.

**Comment by AUK1939** [comment]
I guess it doesn't suprise me, it wouldn't be the only python modules that doesn't work on windows :) Thanks for your input.

**Comment by thrasibule** [comment]
OISRateHelpers have been added.
