### ISSUE TITLE
Build error error: ‘Microsecond’ is not a member of ‘QuantLib’

### ISSUE THREAD

**Issue by Kmanolo** [enthought/pyql#255]
Hello, 

I am trying to build pyql on a fresh installation against Quantlib 1.17, on linux mint 19.2 (ubuntu based linux). Quantlib has build fine and i can run the cpp examples. All header files are under /usr/local/include and Quantlib has been placed under /opt. However i get many errors like the below (all 
of the kind that date types can not be found in the Quantlib namespace): 

quantlib/time/date.cpp:21305:87: error: ‘Microsecond’ is not a member of ‘QuantLib’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(QuantLib::Microsecond value) {
                                                                                       ^~~~~~~~~~~
quantlib/time/date.cpp:21305:87: note: suggested alternative: ‘Microseconds’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_QuantLib_3a__3a_Microsecond(QuantLib::Microsecond value) {
                                                                                       ^~~~~~~~~~~
                                                                                       Microseconds
I have tried to build with the latest version of Cython but also with 0.29.1 and 0.29.2
Is there any advice to get around this ?

Many thanks!

**Comment by thrasibule** [comment]
Your quantlib needs to be built with --enable-intraday.

**Comment by Kmanolo** [comment]
That has worked well, thanks vm!
