### ISSUE TITLE
Missing data in examples/calibrate_heston.py

### ISSUE THREAD

**Issue by tnicolas** [enthought/pyql#61]
It appears that the Heston Calibration example (‘calibrate_heston.py’) is missing it’s ‘df_rates.pkl’ file and therefore doesn’t run.  I was wondering if you might be able to check the necessary file into the examples/data directory of the project.

**Comment by phenaff** [comment]
The issue was fixed in #118 by restructuring the examples. See stovol_calibration.py in examples/scripts.
