### ISSUE TITLE
Compiling error on Win7x64, MSVC 10.0 Express, 32-bit, Python 3.4.1 32bit, QL1.4, Boost 1.55.0

### ISSUE THREAD

**Issue by dr-leo** [enthought/pyql#66]
The following transcript looks like a Py2to3 C API problem:

...

building 'quantlib.indexes.libor' extension
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox
 /MD /W3 /GS- /DNDEBUG -DHAVE_CONFIG_H -D__WIN32__ -DWIN32 -DNDEBUG -D_WINDOWS -
DNOMINMAX -DWINNT -D_WINDLL -D_SCL_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECAT
E -D_SCL_SECURE_NO_WARNINGS -IC:\users\stefan\documents\dev\QuantLib-1.4 -IC:\bo
ost_1_55_0 -I. -I./cpp_layer -IC:\Users\stefan\anaconda3\lib\site-packages\numpy
\core\include -IC:\Users\stefan\anaconda3\lib\site-packages\numpy\core\include -
IC:\Users\stefan\anaconda3\include -IC:\Users\stefan\anaconda3\include /Tpquantl
ib\indexes\libor.cpp /Fobuild\temp.win32-3.4\Release\quantlib\indexes\libor.obj
/GR /FD /Zm250 /EHsc
libor.cpp
quantlib\indexes\libor.cpp(1918) : error C3861: 'PyString_AsString': identifier
not found
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\
cl.exe' failed with exit status 2

**Comment by dpinte** [comment]
Closing now that #35 is merged.
