### ISSUE TITLE
Using quantlib calendar functions kills my python...

### ISSUE THREAD

**Issue by JohnSmizz** [enthought/pyql#79]
Hi-

I am an amateur Python and pyQL and am having some issues with actually using quantlib's useful in-built date capabilities (including calendars).
The text file with the date functionality doesn't explicitly state how and what to import to make the functions and methods work, so I've been trying to do it myself. In the example I am going to show you all I am trying to do is take today's date, and adjust it backward if its NOT a business day. However, as soon as I run the code, I get the "It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

````
from quantlib.time import calendar, date
cal = calendar.UnitedKingdom()
refdate = cal.adjust(date.today(), calendar.Preceding)

````

Thus we have the crash. I can not replicate this if I use calendar.TARGET(). 

Thanks,

**Comment by dpinte** [comment]
@JohnSmizz yes, I can replicate. You found an interesting bug. There was some outdated and incorrect declaration in `calendar.pxd`.  PR is there. Will be merged asap.

Your code should run fine with the following imports:

```
from quantlib.time.api import UnitedKingdom, today, Preceding

cal = UnitedKingdom()
td = today() 
refdate = cal.adjust(td, Preceding)
print refdate
```

or if you prefer not using the api module, you can directly get the UK calendar from `quantlib.time.calendars.united_kingdom` or easy from the `calendar_from_name` function defined in the calendar_registry module.
