### ISSUE TITLE
generate_symbols

### ISSUE THREAD

**Issue by charles-peter** [enthought/pyql#85]
Hey guys been trying to get PYQL to work on windows for the past day or two. I've been following the getting started guided but have been running into a few issues. I can get QuantLib to build but the only the qunatlib part of the solution. Which I think leads to my main issue, where when I try to start the generate_symbols.py I get the error "WindowsError: [Error 2] system cannot find the file specified" this happens durring the first call of the sub process. I Set up the correct file paths for my system and also looked to see if the object files are being built.(Which they are.) I run aground with this and aren't sure where to go. Any help would be appreciated. Thanks.

**Comment by dpinte** [comment]
@charles-peter I guess you haven't installed the mingw package which provides `nm.exe`. I can provide you with the needed dll's and lib file if needed.

**Comment by charles-peter** [comment]
I downloaded MinGW, and made sure that the nm command was useable by running it in my console right in the quantlib release folder. 
I still break at nearly the same point on line 299 in the pydev_monkey.py.
"return getattr(_subprocess, original_name)(appName, patch_arg_str_win(commandLine), *args)"

Is it possible I'm building the objects wrong? I added the declspec(dllexport) to the setting.hpp and changed the project to a dll with .dll extension.

**Comment by charles-peter** [comment]
So I installed mingw using the installer. I tested it within the console.
-Cd to QuantLib\Build\win32\Release
-nm abcd.obj
Then it spit out a bunch of text that seemed like the contents of the .obj

Also I used pycharm to track down the actual line it broke on and it was line 299 in the pydev_monkey.py
"return getattr(_subprocess, original_name)(appName, patch_arg_str_win(commandLine), *args)"

I use the Anacondas version of Python 2.7 which is just python with a bunch of added libraries. Could this be causing a problem? Or do you think it is still the MinGW?(If so getting the exact .dll's and .lib's that I'd need for MinGW would probably fix this issue. )

**Comment by charles-peter** [comment]
NVM I figured it out. I ended up running the python file from the MinGW directory and that seems to of worked. Hopefully I can get the setup.py working correctly now.

**Comment by dpinte** [comment]
Great! closing the ticket.
