### ISSUE TITLE
Extending PyQL - compile issues 

### ISSUE THREAD

**Issue by Kmanolo** [enthought/pyql#95]
Hi, 

I am having some issues in extending PyQl with libor market model and would appreciate some help. I am trying to add LiborForwardModelProcess from ql/legacy following existing examples like swap_index but I get some uninformative cython compilation errors. My .pyx file is 
```
include '../types.pxi'

from cython.operator cimport dereference as deref
cimport _lfm_process as _lfmp


from quantlib.index cimport Index
from quantlib.indexes.ibor_index cimport IborIndex
from quantlib.handle cimport shared_ptr

cimport quantlib._index as _in
cimport quantlib.indexes._ibor_index as _ii
cimport quantlib.processes._stochastic_process as _sp
cdef class LiborForwardModelProcess:
    def __cinit__(self):
        pass


    def __init__(self, Size size_, IborIndex ibor_index ):
        self._thisptr = new shared_ptr[_sp.StochasticProcess](
			new _lfmp.LiborForwardModelProcess(size_,
			                                   deref(<shared_ptr[_ii.IborIndex]*> ibor_index._thisptr )))
```
whereas the cpp-cython header is 
```
include '../types.pxi'

from quantlib.handle cimport shared_ptr
from quantlib.termstructures.yields._flat_forward cimport YieldTermStructure
cimport quantlib._quote as _qt
from quantlib.indexes._ibor_index cimport IborIndex
from quantlib.processes._stochastic_process cimport StochasticProcess

cdef extern from 'ql/legacy/libormarketmodels/lfmprocess.hpp' namespace 'QuantLib': 
    cdef cppclass LiborForwardModelProcess(StochasticProcess):
        LiborForwardModelProcess() # empty constructor 
        LiborForwardModelProcess(Size size, shared_ptr[IborIndex]& index) except + 
        #Size size() except +
```
I am trying to compile this in Ubuntu using Python 2.7 and cython 0.22 but i get the error message : 

Error compiling Cython file:
------------------------------------------------------------
...
    def __cinit__(self):
        pass

    def __init__(self, Size size_, IborIndex ibor_index ):
        self._thisptr = new shared_ptr[_sp.StochasticProcess](
                                                            ^
------------------------------------------------------------

quantlib/legacy/lfm_process.pyx:26:61: Cannot convert 'shared_ptr[StochasticProcess] *' to Python object
Traceback (most recent call last):
  File "setup.py", line 244, in <module>
    ext_modules = collect_extensions(),
  File "setup.py", line 218, in collect_extensions
    for dirpath in cython_extension_directories
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 825, in cythonize
    cythonize_one(*args[1:])
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 944, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: quantlib/legacy/lfm_process.pyx

I would have expected some information on the top of hte error message explaining where the error is coming from, does this make any sense ? Many thanks in advance.

**Comment by dpinte** [comment]
@Kmanolo you need to have a type defined for `_thisptr. If not, Cython will consider that as a Python attribute of your class and thus, it will surely not be able to `Cannot convert 'shared_ptr[StochasticProcess] ' to Python object`. 

Here is an example of definition of the `_thisptr` with a type: https://github.com/enthought/pyql/blob/master/quantlib/termstructures/default_term_structure.pyx#L8

**Comment by Kmanolo** [comment]
Hi @dpinte - thanks for getting back, I should have said that I also have the cython declaration file .pxd ( following again the other examples) : 
```
cimport _lfm_process as _lfmp 
from quantlib.handle cimport shared_ptr 
from quantlib.stochastic_process cimport StochasticProcess

cdef class LiborForwardModelProcess:
    cdef shared_ptr[_lfmp.LiborForwardModelProcess]* _thisptr
```
and it did not work. However moving the definition to the .pyx does the trick! How come this is different than other examples, e.g. heston_process or swap_index ? 

Many thanks.

**Comment by dpinte** [comment]
@Kmanolo it is more than likely a naming issue between your pyx and pxd file.
